config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  match '/help',        to: 'static_pages#help',          via: 'get'
  match '/calculators', to: 'static_pages#calculators',   via: 'get'
  match '/about',		    to: 'static_pages#about',    		  via: 'get'
  match '/signup',	   	to: 'users#new',				          via: 'get'
  match '/login',       to: 'sessions#new',               via: 'get'
  match '/login',       to: 'sessions#create',            via: 'post'
  match '/logout',      to: 'sessions#destroy',           via: 'delete'
  match '/dashboard',   to: 'users#show',                 via: 'get'

  resources :users
  resources :account_activations, only: [:edit]

  get 'sessions/new'
  get 'users/new'

  resources :stocks
  resources :options
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  belongs_to :user

  before_save { self.ticker = ticker.upcase }

  default_scope -> { order('created_at ASC') }
  validates :user_id, presence: true
  validates :shares, presence: true, numericality: {greater_than_or_equal_to: 1.0}
  validates :entryprice, :entryfee, presence: true, numericality: {greater_than_or_equal_to: 0.0001}
  validates :entrydate, presence: true
  validates :ticker, presence: true, length: { maximum: 6 }


  def gross_liquidity
    (shares * entryprice)
  end

  def net_liquidity
    if exitfee?
      gross_liquidity - (entryfee + exitfee)
    else
      gross_liquidity - (entryfee * 2)
    end
  end

  def current_price
    #https://github.com/tyrauber/stock_quote
  end

  def profit_loss_dollars
  end

  def profit_loss_percent
  end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :logged_in_user
  before_action :correct_user, only: :destroy

  def index
    @stocks = current_user.stocks.all
  end

  def show
    @stock = Stock.find(params[:id])
    @history = Stock.where(ticker: params[:ticker])
  end

  def new
    @stock = Stock.new
  end

  def create
    @stock = current_user.stocks.build(stock_params)
    if @stock.save
      flash[:success] = "Stock Added!"
      redirect_to @stock
    else
      render 'new'
    end
  end

  def edit
    @stock = Stock.find(params[:id])
  end

  def update
    @stock = Stock.find(params[:id])
    if @stock.update_attributes(stock_params)
      flash[:success] = "Stock Updated"
      redirect_to @stock
    else
      render 'edit'
    end
  end

  def destroy
    Stock.find(params[:id]).destroy
    flash[:success] = "Stock Deleted"
    redirect_to stocks_path
  end

  private

    def stock_params
      params.require(:stock).permit(:ticker, :shares, :entryprice, :entryfee, :exitprice, :exitfee, :entrydate, :exitdate)
    end

    def correct_user
      @stock = current_user.stocks.find_by(id: params[:id])
      redirect_to root_url if @stock.nil?
    end

end

app/views/stocks/_stock.html.erb
<tr>
  <td><%= link_to stock.ticker, stock %></td>
  <td><%= number_with_precision stock.gross_liquidity, :precision => 2 %></td>
  <td><%= number_with_precision stock.net_liquidity, :precision => 2 %></td>
  <td><%= stock.shares %></td>
  <td><%= number_with_precision stock.entryprice, :precision => 4 %></td>
  <td>{{ current.price }}</td>
  <td>{{ current.pld }}</td>
  <td>{{ current.plp }}</td>
  <td><%= number_to_currency stock.entryfee, :precision => 2 %></td>
  <td><%= stock.entrydate.to_s(:trade_date) %></td>
  <td><%= time_ago_in_words(stock.entrydate) %></td>
  <td>
    <div class="btn-toolbar" role="toolbar">
      <div class="btn-group btn-group-xs" role="group" aria-label="">
        <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-search" aria-hidden="true"></span> <%= link_to 'View', stock %></button>
        <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> <%= link_to 'Edit', edit_stock_path(stock) %></button>
      </div>
    </div>
  </td>
</tr>

app/views/stocks/edit.html.erb
<div class="col-xs-12 col-sm-4 col-sm-offset-4 well">

<h1 class="text-center">Edit Stock</h1>
<br />

<%= form_for(@stock) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <div>
    <%= f.label :entrydate %><br />
    <%= f.date_select :entrydate, {:include_blank => true, :default => nil} %>
  </div>
  <div>
    <%= f.label :ticker %> <%= f.text_field :ticker %>
  </div>
  <div>
    <%= f.label :shares %> <%= f.text_field :shares %>
  </div>
    <div>
    <%= f.label :entryprice %> <%= f.text_field :entryprice %>
  </div>
    <div>
    <%= f.label :entryfee %> <%= f.text_field :entryfee %>
  </div>

<hr />

  <div>
    <%= f.label :exitdate %><br />
    <%= f.date_select :exitdate, {:include_blank => true} %>
  </div>
  <div>
    <%= f.label :exitprice %> <%= f.text_field :exitprice %>
  </div>
    <div>
    <%= f.label :exitfee %> <%= f.text_field :exitfee %>
  </div>

  <br />

  <div>
    <%= f.submit "Save Changes", class: "btn btn-success" %>
  </div>

  <br />

  <div>
    <button type="button" class="btn btn-danger" style="width:100%;color:#fff;"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span> <%= link_to 'Delete Stock', @stock, method: :delete, data: { confirm: 'Are you sure want to delete this holding?  This action cannot be undone!' } %></button>
  </div>

<% end %>

</div>

app/views/stocks/index.html.erb
<!-- title -->

<h3>Stocks
  <button type="button" class="btn btn-xs btn-default">
    <span class="glyphicon glyphicon-plus"></span> <%= link_to 'New Stock', new_stock_path %>
  </button>
</h3>

<table class="table table-striped table-hover" cellpadding="0" cellpadding="0">
  <thead>
    <tr>
      <th scope="col">ticker</th>
      <th scope="col">shares</th>
      <th scope="col">entry $</th>
      <th scope="col">current $</th>
      <th scope="col">p/l $</th>
      <th scope="col">p/l %</th>
      <th scope="col">exit $</th>
      <th scope="col">entry fee</th>
      <th scope="col">exit fee</th>
      <th scope="col">entry date</th>
      <th scope="col">exit date</th>
      <th scope="col">days held</th>
      <th scope="col">actions</th>
    </tr>
  </thead>
  <tbody>

  <% @stocks.each do |stock| %>
    <tr>
      <td><%= link_to stock.ticker, stock %></td>
      <td><%= stock.shares %></td>
      <td><%= number_with_precision stock.entryprice, :precision => 4 %></td>
      <td>{{ cur.price }}</td>
      <td>{{ cur.pld }}</td>
      <td>{{ cur.plp }}</td>
      <td><%= number_with_precision stock.exitprice, :precision => 4 %></td>
      <td><%= number_with_precision stock.entryfee, :precision => 2 %></td>
      <td><%= number_with_precision stock.exitfee, :precision => 2 %></td>
      <td><%= stock.entrydate.to_s(:trade_date) %></td>

      <% if stock.exitdate? %>
        <td><%= stock.exitdate.to_s(:trade_date) %></td>
      <% else %>
        <td></td>
      <% end %>

      <td><%= time_ago_in_words(stock.entrydate) %></td>
      <td>
        <div class="btn-toolbar" role="toolbar">
          <div class="btn-group btn-group-xs" role="group" aria-label="">
            <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-search" aria-hidden="true"></span> <%= link_to 'View', stock %></button>
            <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> <%= link_to 'Edit', edit_stock_path(stock) %></button>
          </div>
        </div>
      </td>
    </tr>
  <% end %>

  </tbody>
</table>

app/views/stocks/new.html.erb
<div class="col-xs-12 col-sm-4 col-sm-offset-4 well">

<h1 class="text-center">New Stock</h1>
<br />

<%= form_for(@stock) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <div>
    <%= f.label :entrydate %><br />
    <%= f.date_select :entrydate %>
  </div>
  <div>
    <%= f.label :ticker %> <%= f.text_field :ticker %>
  </div>
  <div>
    <%= f.label :shares %> <%= f.text_field :shares %>
  </div>
    <div>
    <%= f.label :entryprice %> <%= f.text_field :entryprice %>
  </div>
    <div>
    <%= f.label :entryfee %> <%= f.text_field :entryfee %>
  </div>

  <br />

  <div>
    <%= f.submit "Add Stock", class: "btn btn-success" %>
  </div>

<% end %>

</div>

app/views/stocks/show.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-4">

    <div class="btn-group btn-group-xs" role="group" aria-label="">
      <%= link_to '<- Back to Stocks', stocks_path, class: "btn btn-default" %>
    </div>

    <h1><%= @stock.ticker %></h1>

    <table class="table table-striped" cellpadding="0" cellpadding="0">
      <tr>
        <th scope="row">Current</th>
        <td>{{ cur.price }}</td>
      </tr>
      <tr>
        <th scope="row">Shares</th>
        <td><%= @stock.shares %></td>
      </tr>
      <tr>
        <th scope="row">Entry $</th>
        <td><%= number_with_precision @stock.entryprice, :precision => 4 %></td>
      </tr>
      <tr>
        <th scope="row">Entry fee</th>
        <td><%= number_to_currency @stock.entryfee %></td>
      </tr>
      <tr>
        <th scope="row">Gross Liquidity</th>
        <td><%= number_to_currency @stock.gross_liquidity, :precision => 2 %></td>
      </tr>
      <tr>
        <th scope="row">Net Liquidity</th>
        <td><%= number_to_currency @stock.net_liquidity, :precision => 2 %></td>
      </tr>
      <tr>
        <th scope="row">Entry Date</th>
        <td><%= @stock.entrydate.to_s(:trade_date) %></td>
      </tr>
      <tr>
        <th scope="row">Days Held</th>
        <td><%= time_ago_in_words(@stock.entrydate) %></td>
      </tr>

      <% if @stock.exitdate %>
        <tr>
          <th scope="row">Exit Date</th>
          <td><%= @stock.exitdate.to_s(:trade_date) %></td>
        </tr>
      <% end %>

      <% if @stock.exitprice %>
        <tr>
          <th scope="row">Exit $</th>
          <td><%= number_to_currency @stock.exitprice, :precision => 4 %></td>
        </tr>
      <% end %>

      <% if @stock.exitfee %>
        <tr>
          <th scope="row">Exit fee</th>
          <td><%= number_to_currency @stock.exitfee %></td>
        </tr>
      <% end %>

    </table>

    <div class="btn-toolbar" role="toolbar">
      <div class="btn-group btn-group-xs" role="group" aria-label="">
        <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> <%= link_to 'New Stock', new_stock_path%></button>
        <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> <%= link_to 'Edit', edit_stock_path(@stock) %></button>
      </div>
    </div><!-- /.btn-toolbar -->
  </div><!-- /.col-md-4 -->

  <div class="col-xs-12 col-sm-8">
    {{ charts }}
    <br />
    {{ charts }}
  </div><!-- /.col-md-8 -->

</div><!-- /.row -->


<br /><br />


<div class="row">
  <div class="container">

    <h3><%= @stock.ticker %> History</h3>

    <hr />

    <%= render 'shared/history_stocks' %>

  </div><!-- /.container -->
</div><!-- /.row -->