config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  match '/help',        to: 'static_pages#help',          via: 'get'
  match '/calculators', to: 'static_pages#calculators',   via: 'get'
  match '/about',		    to: 'static_pages#about',    		  via: 'get'
  match '/signup',	   	to: 'users#new',				          via: 'get'
  match '/login',       to: 'sessions#new',               via: 'get'
  match '/login',       to: 'sessions#create',            via: 'post'
  match '/logout',      to: 'sessions#destroy',           via: 'delete'
  match '/dashboard',   to: 'users#show',                 via: 'get'

  resources :users
  resources :account_activations, only: [:edit]

  get 'sessions/new'
  get 'users/new'

  resources :stocks
  resources :options
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :stocks, dependent: :destroy
  has_many :options, dependent: :destroy

  attr_accessor :remember_token, :activation_token

  before_save :downcase_email
  before_create :create_activation_digest

  validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 },
		                                format: { with: VALID_EMAIL_REGEX },
		                                uniqueness: { case_sensitive: false }
	validates :password, length: { minimum: 6 }, allow_blank: true

  has_secure_password


  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
                                                  BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
  	SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
  	return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
  	update_attribute(:remember_digest, nil)
  end


  private

    def downcase_email
      self.email = email.downcase
    end

    def create_activation_digest
      self.activation_token = User.new_token
      self.activation_digest = User.digest(activation_token)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: [:index, :destroy]

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
  	@user = User.find(params[:id])
    @stocks = @user.stocks.paginate(page: params[:page])
    @options = @user.options.paginate(page: params[:page])
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      log_in @user
  		flash[:success] = "Welcome to myMarket"
  		redirect_to @user
  	else
  		render 'new'
  	end
  end

  def edit
    @user = User.find(params[:id])
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User removed"
    redirect_to users_url
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end


  private

  	def user_params
  		params.require(:user).permit(:name, :email, :password, :password_confirmation)
  	end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.try(:admin?)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_portfolio_options.html.erb
<h3>Options Holdings</h3>
<table id="options-portfolio" border="1" style="font-size:11px;">
<thead>
    <tr>
        <th>ticker</th>
        <th>side</th>
        <th>type</th>
        <th>contracts</th>
        <th>size</th>
        <th>expiration</th>
        <th>strike</th>
        <th>entry</th>
        <th>b fee</th>
        <th>exit</th>
        <th>s fee</th>
        <th>loss limit</th>
        <th>gain limit</th>
        <th>net in</th>
        <th>total in</th>
        <th>gross out</th>
        <th>net out</th>
        <th>total fees</th>
        <th>p/l $</th>
        <th>p/l %</th>
    </tr>
</thead>
<tbody>
    <tr>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
    </tr>
    <tr>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
    </tr>
    <tr>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
    </tr>
</tbody>
</table>

app/views/users/_portfolio_stock.html.erb
<table class="table" cellpadding="0" cellpadding="0">
  <thead>
    <tr>
      <th>ticker</th>
      <th>shares</th>
      <th>entry $</th>
      <th>entry fee</th>
      <th>exit $</th>
      <th>exit fee</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @stocks.ticker %></td>
      <td><%= @stocks.shares %></td>
      <td><%= number_with_precision @stocks.entryprice, :precision => 4 %></td>
      <td><%= number_with_precision @stocks.entryfee, :precision => 2 %></td>
      <td><%= number_with_precision @stocks.exitprice, :precision => 4 %></td>
      <td><%= number_with_precision @stocks.exitfee, :precision => 2 %></td>
    </tr>
  </tbody>
</table>

app/views/users/_transactions_options.html.erb
<h3>Options Transactions</h3>
<table id="options-portfolio" border="1" style="font-size:11px;">
<thead>
    <tr>
        <th>ticker</th>
        <th>side</th>
        <th>type</th>
        <th>contracts</th>
        <th>size</th>
        <th>expiration</th>
        <th>strike</th>
        <th>entry</th>
        <th>b fee</th>
        <th>exit</th>
        <th>s fee</th>
        <th>loss limit</th>
        <th>gain limit</th>
        <th>net in</th>
        <th>total in</th>
        <th>gross out</th>
        <th>net out</th>
        <th>total fees</th>
        <th>p/l $</th>
        <th>p/l %</th>
    </tr>
</thead>
<tbody>
    <tr>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
    </tr>
    <tr>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
    </tr>
    <tr>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
        <td>{{ data }}</td>
    </tr>
</tbody>
</table>

app/views/users/_transactions_stock.html.erb
<h3>Stock Transactions</h3>
    <table id="stock-portfolio" border="1" style="font-size:11px;">
    <thead>
        <tr>
            <th>ticker</th>
            <th>shares</th>
            <th>entry price</th>
            <th>b/s signal</th>
            <th>last price</th>
            <th>day change %</th>
            <th>target price</th>
            <th>stop</th>
            <th>pos change</th>
            <th>pos change %</th>
            <th>Invest</th>
            <th>mkt value $</th>
            <th>fee b&s</th>
            <th>cost basis</th>
            <th>Unrealised Gain/Loss</th>
            <th>Unrealised Gain/Loss (%)</th>
            <th>% cost</th>
            <th>% port</th>
            <th>% gain goal</th>
            <th>% max loss</th>
            <th>proj delta $</th>
            <th>delta %</th>
            <th>act delta $</th>
            <th>shares to add</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
        </tr>
        <tr>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
        </tr>
        <tr>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
            <td>{{ data }}</td>
        </tr>
    </tbody>
</table>

app/views/users/_user.html.erb
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
	  	<% if current_user.admin? && !current_user?(user) %>
	  		| <%= link_to "delete", user, method: :delete, data: { confirm: "You sure?" } %>
			<% end %>
    </li>
  <% end %>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>

<div class="row">
	<div class="col-sm-6 col-sm-offset-3 well">
		<h1 class="text-center">Update your profile</h1>

		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>

			<%= f.label :name %>
			<%= f.text_field :name, class: 'form-control' %>

			<%= f.label :email %>
			<%= f.text_field :email, class: 'form-control' %>

			<%= f.label :password %>
			<%= f.password_field :password, class: 'form-control' %>

			<%= f.label :password_confirmation, "Confirmation" %>
			<%= f.password_field :password_confirmation, class: 'form-control' %>

			<%= f.submit "Save changes", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>


<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<div class="row">
	<div class="col-sm-6 col-sm-offset-3 well">
		<h1 class="text-center">Sign up</h1>

		<br />

		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>

			<div class="input-group">
				<span class="input-group-addon">
					<span class="glyphicon glyphicon-user"></span>
				</span>
				<%= f.text_field :name, placeholder: "Name", class: 'form-control' %>
			</div>

<br />

			<div class="input-group">
				<span class="input-group-addon">
					<span class="glyphicon glyphicon-envelope"></span>
				</span>
				<%= f.text_field :email, placeholder: "Email", class: "form-control" %>
			</div>

<br />

			<div class="input-group">
				<span class="input-group-addon">
					<span class="glyphicon glyphicon-lock"></span>
				</span>
				<%= f.password_field :password, placeholder: "Password", class: "form-control" %>
			</div>

<br />

			<div class="input-group">
				<span class="input-group-addon">
					<span class="glyphicon glyphicon-lock"></span>
				</span>
				<%= f.password_field :password_confirmation, placeholder: "Password Confirmation", class: 'form-control' %>
			</div>

<br />

			<%= f.submit "Create Account", class: "btn btn-success" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="row">
		<div class="container-fluid">

			<div role="navigation">
				<ul class="nav nav-justified" style="border-bottom: 2px solid #ccc;margin-bottom: 20px;">
					<li><%= link_to 'Portfolio',		'#' %></li>
					<li><%= link_to 'Transactions',	'#' %></li>
					<li><%= link_to 'Performance',	'#' %></li>
					<li><%= link_to 'Watchlists',		'#' %></li>
				</ul>
			</div>

		</div><!-- /.container -->
</div><!-- /.row -->


<div class="row">
	<div class="col-sm-12">

		<% if @user.options.any? %>
		<h3><%= link_to 'Options', options_path %> <%= link_to 'Add New Option', new_option_path, class: 'btn btn-primary btn-xs' %></h3>
		<table class="table table-striped table-hover wide-data-table" cellpadding="0" cellpadding="0">
		  <thead>
		    <tr>
		      <th scope="col">ticker</th>
		      <th scope="col">gross liq</th>
		      <th scope="col">net liq</th>
		      <th scope="col">b/s</th>
		      <th scope="col">c/p</th>
		      <th scope="col">contracts</th>
		      <th scope="col">size</th>
		      <th scope="col">expiration</th>
		      <th scope="col">strike</th>
		      <th scope="col">entry$</th>
		      <th scope="col">b fee</th>
		      <th scope="col">entry date</th>
		      <th scope="col">days held</th>
		      <th scope="col">actions</th>
		    </tr>
		  </thead>
		  <tbody>

			<%= render @options %>

		  </tbody>
			<tfoot>
				<tr>
		      <th scope="col"><%= @user.options.count %></th>
		      <th scope="col">{{ gross liq }}</th>
		      <th scope="col">{{ net liq }}</th>
		      <th scope="col">{{ #b/#s }}</th>
		      <th scope="col">{{ #c/#p }}</th>
		      <th scope="col">{{ t.con }}</th>
		      <th scope="col" class="wide-data-no-data"></th>
		      <th scope="col" class="wide-data-no-data"></th>
		      <th scope="col" class="wide-data-no-data"></th>
		      <th scope="col" class="wide-data-no-data"></th>
		      <th scope="col">{{ t.fee }}</th>
		      <th scope="col"></th>
		      <th scope="col">{{ avg.days }}</th>
		      <th scope="col" class="wide-data-no-data"></th>
		    </tr>
				</tr>
			</tfoot>
		</table>
		<% end %>


		<% if @user.stocks.any? %>
			<h3><%= link_to 'Stocks', stocks_path %> <%= link_to 'Add New Stock', new_stock_path, class: 'btn btn-primary btn-xs' %></h3>
			<table class="table table-striped table-hover wide-data-table" cellpadding="0" cellpadding="0">
			  <thead>
			    <tr>
			      <th scope="col">ticker</th>
						<th scope="col">gross liq</th>
			      <th scope="col">net liq</th>
			      <th scope="col">shares</th>
			      <th scope="col">entry $</th>
			      <th scope="col">current</th>
			      <th scope="col">p/l $</th>
			      <th scope="col">p/l %</th>
			      <th scope="col">entry fee</th>
			      <th scope="col">entry date</th>
			      <th scope="col">days held</th>
			      <th scope="col">actions</th>
			    </tr>
			  </thead>
			  <tbody>

					<%= render @stocks %>

			  </tbody>
			  <tfoot>
			  	<tr>
			  		<th scope="col"><%= @user.stocks.count %></th>
						<th scope="col">{{ gross.liq }}</th>
			      <th scope="col">{{ net.liq }}</th>
			      <th scope="col" class="wide-data-no-data"></th>
			      <th scope="col" class="wide-data-no-data"></th>
			      <th scope="col" class="wide-data-no-data"></th>
			      <th scope="col">{{ total.pld }}</th>
			      <th scope="col">{{ total.plp }}</th>
			      <th scope="col">{{ total.fees }}</th>
			      <th scope="col" class="wide-data-no-data"></th>
			      <th scope="col">{{ avg.days }}</th>
			      <th scope="col" class="wide-data-no-data"></th>
			  	</tr>
			  </tfoot>
			</table>
		<% end %>


<!--	<h1>Transactions</h1> -->
<!-- see _transaction partials -->
<!--		<h4>Options</h4>
<br />
		<h4>Stock</h4>
-->
	</div><!-- /.col-sm-10 -->


</div><!-- /.row -->