config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  match '/help',        to: 'static_pages#help',          via: 'get'
  match '/calculators', to: 'static_pages#calculators',   via: 'get'
  match '/about',		    to: 'static_pages#about',    		  via: 'get'
  match '/signup',	   	to: 'users#new',				          via: 'get'
  match '/login',       to: 'sessions#new',               via: 'get'
  match '/login',       to: 'sessions#create',            via: 'post'
  match '/logout',      to: 'sessions#destroy',           via: 'delete'
  match '/dashboard',   to: 'users#show',                 via: 'get'

  resources :users
  resources :account_activations, only: [:edit]

  get 'sessions/new'
  get 'users/new'

  resources :stocks
  resources :options
end

app/models/option.rb
class Option < ActiveRecord::Base
  belongs_to :user

  before_save { self.ticker = ticker.upcase }

  validates :user_id, :side, :optiontype, :entrydate, presence: true
  validates :contracts, :size, presence: true, numericality: {greater_than_or_equal_to: 1.0}
  validates :entryfee, presence: true, numericality: {greater_than_or_equal_to: 0.01}
  validates :entryprice, presence: true, numericality: {greater_than_or_equal_to: 0.0001}
  validates :ticker, presence: true, length: { maximum: 6 }


  def gross_liquidity
    (contracts * size) * entryprice
  end

  def net_liquidity
    if exitfee?
      gross_liquidity - (entryfee + exitfee)
    else
      gross_liquidity - (entryfee * 2)
    end
   end

end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
  before_action :logged_in_user
  before_action :correct_user, only: :destroy

  def index
    @options = current_user.options.all
  end

  def show
    @option = Option.find(params[:id])
  end

  def new
    @option = Option.new
  end

  def create
    @option = current_user.options.build(option_params)
    if @option.save
      flash[:success] = "Option Added!"
      redirect_to @option
    else
      render 'new'
    end
  end

  def edit
    @option = Option.find(params[:id])
  end

  def update
    @option = Option.find(params[:id])
    if @option.update_attributes(option_params)
      flash[:success] = "Option Update"
      redirect_to @option
    else
      render 'edit'
    end
  end

  def destroy
    Option.find(params[:id]).destroy
    flash[:success] = "Option Deleted"
    redirect_to options_path
  end

  private

    def option_params
      params.require(:option).permit(:ticker, :side, :optiontype, :expiration, :contracts, :size, :strike, :entryprice, :entryfee, :exitprice, :exitfee, :entrydate, :exitdate)
    end

    def correct_user
      @option = current_user.options.find_by(id: params[:id])
      redirect_to root_url if @option.nil?
    end

end

app/views/options/_option.html.erb
<tr>
  <td><%= link_to option.ticker, option %></td>
  <td><%= number_to_currency option.gross_liquidity %></td>
  <td><%= number_to_currency option.net_liquidity %></td>
  <td><%= option.side %></td>
  <td><%= option.optiontype %></td>
  <td><%= option.contracts %></td>
  <td><%= option.size %></td>
  <td><%= option.expiration %></td>
  <td><%= option.strike %></td>
  <td><%= option.entryprice %></td>
  <td><%= option.entryfee %></td>
  <td><%= option.entrydate.to_s(:trade_date) %></td>
  <td><%= time_ago_in_words(option.entrydate) %></td>
  <td>
    <div class="btn-toolbar" role="toolbar">
      <div class="btn-group btn-group-xs" role="group" aria-label="">
        <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-search" aria-hidden="true"></span> <%= link_to 'View', option %></button>
        <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> <%= link_to 'Edit', edit_option_path(option) %></button>
      </div>
     </div>
  </td>
</tr>

app/views/options/edit.html.erb
<div class="col-xs-12 col-sm-4 col-sm-offset-4 well">

<h1 class="text-center">Edit Option</h1>

<%= form_for(@option) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <div>
    <%= f.label :entrydate %><br />
    <%= f.date_select :entrydate, {:include_blank => true, :default => nil} %>
  </div>
  <div>
    <%= f.label :ticker %><br />
    <%= f.text_field :ticker %>
  </div>
  <div>
    <%= f.radio_button :side, "Call" %>  <%= f.label :side_call, "Call" %>
    <%= f.radio_button :side, "Put" %>  <%= f.label :side_put, "Put" %>
  </div>
  <div>
    <%= f.radio_button :optiontype, "Buy" %>  <%= f.label :optiontype_buy, "Buy" %>
    <%= f.radio_button :optiontype, "Sell" %>  <%= f.label :optiontype_sell, "Sell" %>
  </div>
  <div>
    <%= f.label :expiration %><br />
    <%= f.text_field :expiration %>
  </div>
  <div>
    <%= f.label :contracts %><br />
    <%= f.number_field :contracts, in: 1..100000, step: 1 %>
  </div>
   <div>
    <%= f.label :size %><br />
    <%= f.number_field :size %>
  </div>
   <div>
    <%= f.label :strike %><br />
    <%= f.number_field :strike, in: 0..2000, step: 0.5 %>
  </div>
  <div>
    <%= f.label :entryprice %><br />
    <%= f.text_field :entryprice %>
  </div>
  <div>
    <%= f.label :entryfee %><br />
    <%= f.text_field :entryfee %>
  </div>

<hr />

  <div>
    <%= f.label :exitdate %><br />
    <%= f.date_select :exitdate, {:include_blank => true} %>
  </div>
  <div>
    <%= f.label :exitprice %><br />
    <%= f.text_field :exitprice %>
  </div>
  <div>
    <%= f.label :exitfee %><br />
    <%= f.text_field :exitfee %>
  </div>

  <br />

  <div>
    <%= f.submit "Update Option", class: "btn btn-success" %>
  </div>

  <br />

  <div>
    <button type="button" class="btn btn-danger" style="width:100%;color:#fff;"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span> <%= link_to 'Delete Option', @option, method: :delete, data: { confirm: 'Are you sure want to delete this holding?  This action cannot be undone!' } %></button>
  </div>

<% end %>

</div>

app/views/options/index.html.erb
<!-- title -->

<h3>Options
  <button type="button" class="btn btn-xs btn-default">
    <span class="glyphicon glyphicon-plus"></span> <%= link_to 'New Option', new_option_path %>
  </button>
</h3>

<table class="table table-striped table-hover text-center" cellpadding="0" cellpadding="0">
  <thead>
    <tr>
      <th scope="col">ticker</th>
      <th scope="col">b/s</th>
      <th scope="col">c/p</th>
      <th scope="col">contracts</th>
      <th scope="col">size</th>
      <th scope="col">expiration</th>
      <th scope="col">strike</th>
      <th scope="col">entry$</th>
      <th scope="col">exit $</th>
      <th scope="col">b fee</th>
      <th scope="col">s fee</th>
      <th scope="col">en date</th>
      <th scope="col">ex date</th>
      <th scope="col">days held</th>
      <th scope="col">actions</th>
    </tr>
  </thead>
  <tbody>

  <% @options.each do |option| %>
    <tr>
      <td><%= link_to option.ticker, option %></td>
      <td><%= option.side %></td>
      <td><%= option.optiontype %></td>
      <td><%= option.contracts %></td>
      <td><%= option.size %></td>
      <td><%= option.expiration %></td>
      <td><%= option.strike %></td>
      <td><%= option.entryprice %></td>
      <td><%= option.exitprice %></td>
      <td><%= option.entryfee %></td>
      <td><%= option.exitfee %></td>
      <td><%= option.entrydate.to_s(:trade_date) %></td>

      <% if option.exitdate? %>
        <td><%= option.exitdate.to_s(:trade_date) %></td>
      <% else %>
        <td></td>
      <% end %>

      <td><%= time_ago_in_words(option.entrydate) %></td>
      <td>
        <div class="btn-toolbar" role="toolbar">
          <div class="btn-group btn-group-xs" role="group" aria-label="">
            <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-search" aria-hidden="true"></span> <%= link_to 'View', option %></button>
            <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> <%= link_to 'Edit', edit_option_path(option) %></button>
          </div>
         </div>
      </td>
    </tr>
  <% end %>

  </tbody>
</table>

app/views/options/new.html.erb
<div class="col-xs-12 col-sm-4 col-sm-offset-4 well">

<h1 class="text-center">New Option</h1>

<%= form_for(@option) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>


  <div>
    <%= f.label :entrydate %><br />
    <%= f.date_select :entrydate %>
  </div>
  <div>
    <%= f.label :ticker %> <%= f.text_field :ticker %>
  </div>
  <div>
    <%= f.radio_button :side, "call" %>  <%= f.label :side_call, "call" %>
    <%= f.radio_button :side, "put" %>  <%= f.label :side_put, "put" %>
  </div>
  <div>
    <%= f.radio_button :optiontype, "buy" %>  <%= f.label :optiontype_buy, "buy" %>
    <%= f.radio_button :optiontype, "sell" %>  <%= f.label :optiontype_sell, "sell" %>
  </div>
  <div>
    <%= f.label :expiration %> <%= f.date_field :expiration %>
  </div>
  <div>
    <%= f.label :contracts, "Contract(s)" %> <%= f.text_field :contracts %>
  </div>
   <div>
    <%= f.label :size %> <%= f.number_field :size, :placeholder => '100', :input_html => { :value => '100' } %>
  </div>
   <div>
    <%= f.label :strike %> <%= f.number_field :strike, in: 0..2000, step: 0.5 %>
  </div>
  <div>
    <%= f.label :entryprice %> <%= f.text_field :entryprice %>
  </div>
  <div>
    <%= f.label :entryfee %> <%= f.text_field :entryfee %>
  </div>

<br />

  <div>
    <%= f.submit "Add option", class: "btn btn-success" %>
  </div>

<% end %>

</div>

app/views/options/show.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-4">

    <div class="btn-group btn-group-xs" role="group" aria-label="">
      <%= link_to '<- Back to Options', options_path, class: "btn btn-default" %>
    </div>

    <h1><%= @option.ticker %></h1>

    <table class="table table-striped" cellpadding="0" cellpadding="0">
        <tr>
          <th scope="row">Buy/Sell</th>
          <td><%= @option.side %></td>
        </tr>
        <tr>
          <th scope="row">Call/Put</th>
          <td><%= @option.optiontype %></td>
        </tr>
        <tr>
          <th scope="row">Contracts</th>
          <td><%= @option.contracts %></td>
        </tr>
        <tr>
          <th scope="row">Size</th>
          <td><%= @option.size %></td>
        </tr>
        <tr>
          <th scope="row">Expiration</th>
          <td><%= @option.expiration %></td>
        </tr>
        <tr>
          <th scope="row">Strike</th>
          <td><%= @option.strike %></td>
        </tr>
        <tr>
          <th scope="row">Entry $</th>
          <td><%= @option.entryprice %></td>
        </tr>
        <tr>
          <th scope="row">Entry Fee</th>
          <td><%= number_to_currency @option.entryfee %></td>
        </tr>
        <tr>
          <th scope="row">Gross Liquidity</th>
          <td><%= number_to_currency @option.gross_liquidity %></td>
        </tr>
        <tr>
          <th scope="row">Net Liquidity</th>
          <td><%= number_to_currency @option.net_liquidity %></td>
        </tr>

        <tr>
          <th scope="row">Entry Date</th>
          <td><%= @option.entrydate.to_s(:trade_date) %></td>
        </tr>
        <tr>
          <th scope="row">Days Held</th>
          <td><%= time_ago_in_words(@option.entrydate) %></td>
        </tr>

        <% if @option.exitdate %>
          <tr>
            <th scope="row">Exit Date</th>
            <td><%= @option.exitdate.to_s(:trade_date) %></td>
          </tr>
        <% end %>

        <% if @option.exitprice %>
          <tr>
            <th scope="row">Exit $</th>
            <td><%= @option.exitprice %></td>
          </tr>
        <% end %>

        <% if @option.exitfee %>
          <tr>
            <th scope="row">Sell fee</th>
            <td><%= @option.exitfee %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <div class="btn-toolbar" role="toolbar">
      <div class="btn-group btn-group-xs" role="group" aria-label="">
        <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> <%= link_to 'Add', new_option_path%></button>
        <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> <%= link_to 'Edit', edit_option_path(@option) %></button>
      </div>
    </div><!-- /.btn-toolbar -->

  </div><!-- /.col-md-4 -->

  <div class="col-xs-12 col-sm-8">
    {{ charts }}
    <br />
    {{ charts }}
  </div><!-- /.col-sm-8 -->

</div><!-- /.row -->

<br /><br />

<div class="row">
  <div class="container">


<h3><%= @option.ticker %> History</h3>

<hr />

<%= render 'shared/history_options' %>

  </div><!-- /.container -->
</div><!-- /.row -->