config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  match '/help',        to: 'static_pages#help',          via: 'get'
  match '/calculators', to: 'static_pages#calculators',   via: 'get'
  match '/about',		    to: 'static_pages#about',    		  via: 'get'
  match '/signup',	   	to: 'users#new',				          via: 'get'
  match '/login',       to: 'sessions#new',               via: 'get'
  match '/login',       to: 'sessions#create',            via: 'post'
  match '/logout',      to: 'sessions#destroy',           via: 'delete'
  match '/dashboard',   to: 'users#show',                 via: 'get'

  resources :users
  resources :account_activations, only: [:edit]

  get 'sessions/new'
  get 'users/new'

  resources :stocks
  resources :options
end

app/views/layouts/_footer.html.erb
<footer class="container-fluid">
	<nav class="navbar">
		<ul class="nav navbar-nav navbar-right">

		<% if logged_in? %>
            <li><%= link_to "Users", users_path %></li>
         <% end %>

            <li><%= link_to "About", about_path %></li>
			<li><%= link_to "Help",  help_path %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header>

		<nav class="navbar navbar-default navbar-static-top" role="navigation">
			<div class="container">
				<div class="navbar-header">
					<%= link_to "myMarket", root_path, class: "navbar-brand" %>
				</div>

			<ul class="nav navbar-nav navbar-right">

			<% if logged_in? %>
				<li><%= link_to "Stocks",				stocks_path %></li>
				<li><%= link_to "Options",			options_path %></li>
				<li><%= link_to "Calculators",	calculators_path %></li>
				<li><%= link_to "Dashboard",		current_user %></li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %> <b class="caret"></b></a>

					<ul class="dropdown-menu">
						<li><%= link_to "Settings", 		'#' %></li>
						<li><%= link_to "Edit info",		edit_user_path(current_user) %></li>
						<li class="divider"></li>
						<li><%= link_to "Log out",			logout_path, method: "delete" %></li>
					</ul>

				</li>

			<% else %>

				<li><%= link_to "Sign up",		signup_path %></li>
				<li><%= link_to "Log in",		login_path %></li>

			<% end %>

			</ul>

			</div><!-- /.container-fluid -->
		</nav>

</header>

app/views/layouts/_ie.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script> 
<![endif]-->

app/views/layouts/angular.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyMarket</title>


  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>

<%= stylesheet_link_tag 'application', media: 'all',
                                       'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>

<%= render 'layouts/ie' %>

</head>
<body>

	<%= render 'layouts/header' %>

  <div class="row">
  	<div class="container">
  		<% flash.each do |message_type, message| %>
      	<div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

  		<%= yield %>

  	</div><!-- /.container-fluid -->
  </div><!-- /.row -->


	<%= render 'layouts/footer' %>
 	<%= debug(params) if Rails.env.development? %>

</body>
</html>